name: Build and Test

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run tests
      run: |
        make docker-container
        make docker-build
