name: Docker Build

on:
  pull_request:
    branches: [ "main" ]

jobs:
  docker_build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: build container
        run: make docker-container

      - name: build project
        run: make docker-build

      #- name: Transfer binaries to Windows
        #uses: actions/upload-artifact@v4
        #with:
          #name: binaries
          #path: bin

  #trigger_windows_unit_test:
    #needs: [docker_build]
    #runs-on: ubuntu-22.04
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}

    #steps:
      #- name: Trigger Windows Test
        #uses: peter-evans/repository-dispatch@v2
        #with:
          #repository: 0xvpr/vpr-pidjeon
          #token: ${{ secrets.GITHUB_TOKEN }}
          #event-type: windows_unit_test
