name: Windows Test

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    needs: docker_build
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download binaries
        uses: actions/download-artifact@v3
        with:
          name: binaries

      - name: Run tests with cmd
        run: |
          ./run-tests.exe
