name: Windows Test

on:
  check_suite:
    types:
      - completed

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download binaries
        uses: actions/download-artifact@v3
        with:
          name: binaries

      - name: Run unit tests
        run: ./run-tests.exe

  update-pull-request:
    needs: test
    if: ${{ github.event.check_suite.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update pull request
        uses: actions/github-script@v4
        with:
          script: |
            github.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.check_suite.pull_requests[0].number,
              body: 'Tests passed successfully!'
            })
