name: Windows Test

on:
  pull_request:
    branches: [ "main" ]

jobs:
  trigger_docker_build:
    runs-on: ubuntu-22.04
    steps:
      - name: Trigger Docker Build
        uses: peter-evans/repository-dispatch@v2
        with:
          repository: 0xvpr/vpr-pidjeon
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: docker_build

  test:
    needs: [trigger_docker_build]
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download binaries
        uses: actions/download-artifact@v3
        with:
          name: binaries

      - name: Run tests with cmd
        run: |
          ./run-tests.exe
