name: Windows Test

on:
  workflow_run:
    workflows: [ "Docker Build" ]
    types:
      - completed

jobs:
  test:
    needs: docker_build.outputs.uploaded
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download binaries
        uses: actions/download-artifact@v3
        with:
          name: binaries

      - name: Run tests with cmd
        run: ./run-tests.exe
