name: Windows Unit Tests

on:
  pull_request:
    branches: [ "main" ]
  workflow_run:
    workflows: ["Docker Build"]
    types:
      - completed

jobs:
  windows_unit_tests:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        if: ${{ github.event_name == 'pull_request' && github.ref == 'refs/heads/main' && github.event.workflow_run.event == 'completed' }}
        uses: actions/checkout@v3

      - name: Download binaries
        uses: actions/download-artifact@v3
        with:
          name: binaries

      - name: Execute CUnit tests
        run: ./run-tests.exe
